### ISSUE TITLE
could the indent guides be just a little brighter?

### ISSUE THREAD

**Issue by rcrooks** [erickmerchant/blacksmith-syntax#1]
Hi @erickmerchant ,

I love this theme and this isn't really a bug, just a small request: could you make the indent guide color just slightly brighter? 

Thanks for considering,
Robert

**Comment by erickmerchant** [comment]
Glad you like it! It's my first Atom theme. So I had never turned indent guides on in Atom, but I just did a commit to lighten them and published a new version. Hope it helps.

**Comment by rcrooks** [comment]
Thanks!
